version: '3.8'
services:
    db:
        image: postgres:15.3-alpine3.18
        restart: "unless-stopped"
        environment:
            - POSTGRES_USER={SUPERUSER_USER}
            - POSTGRES_PASSWORD={SUPERUSER_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
            - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
            - TZ=Europe/Moscow
        volumes:
            - "./docker/pg/data:/var/lib/postgresql/data"
            - "./docker/pg/init:/docker-entrypoint-initdb.d"
            - "./docker/pg/dump:/var/lib/postgresql/dump"
    dating_app:
        image: "dating_app:latest"
        build: .
        stop_signal: SIGINT
        environment:
            - TZ=Europe/Moscow
        restart: "unless-stopped"
        ports:
            - 8000:8000
        env_file: .env
        depends_on:
            - db